### ISSUE TITLE
Pinball - user pages

### ISSUE THREAD

**Issue by emb417** [emb417/metaforiq-next#15]
Click/tap a username and go to a page with current place in season, week, other stats and charts.

**Comment by Banzaibill17** [comment]
Really cool what you are doing for the pinball community, if i come up with something to add i will let you know....

Maybe a user page should be linked to the highscore corner, and show a position based to number off all members and position on all available tables.

 This should encourage people to play as many tables that they could possibly find, and post a score in the highscore corner.
 The more different tables you play and post. The higher you end up in score/exp.

 Maybe even some sort of "User" unplayed/posted a score generator, could be added. So you can see which tables to play, to improve your overall "user" score/exp

**Comment by emb417** [comment]
From Banzaibill17

> To make people play more tables they don't have, some command to the bot like "Surprise me" then the bot should come with a random table to play with a 1 hour countdown. At that point you have one hour to download the table if not already owned, and post the high score to the list. This requires the creator of the bot to participate in this. And on top of that your listings are used to show Ranking

**Comment by emb417** [comment]
Maybe show a distribution of the day of week where high score was posted across all weeks. For example, I believe I post high scores most often on Wednesdays.

**Comment by Banzaibill17** [comment]
Giving a weekly update on a players profile makes sense.
But it needs people to play more different tables on the highscore corner. Otherwise it shows the same thing as the competition corner.

Maybe some other  corners could be added to the discord  channel like:

-Daily Challenge Corner (Bot random Pick)
- Member Birthday Table (member sets up his/her birthday and a favorite table to play on that date)
All members can play that table and join the party.

**Comment by emb417** [comment]
I started #19 to capture the high score corner ideas. I'm going to close this with the basic stats and charts in place.
